version: '3.4'
networks:
    default:
        external:
            name: db_default

services:
    ewhale:
      container_name: ewhale
      environment:
        AWS_KEY: ''
        AWS_REGION: ''
        AWS_SECRET: 
        SYMFONY_ENV: prod
        APP_DB_DRIVER: pdo_mysql
        APP_DB_HOST: db
        APP_DB_NAME: ewhale
        APP_DB_PASSWORD: root
        APP_DB_PORT: 3306
        APP_DB_USER: root
        APP_HOSTNAME:
        APP_IS_INSTALLED: 'true'
        APP_MAILER_TRANSPORT: smtp
        APP_MAILER_HOST: ''
        APP_MAILER_PORT: 587
        APP_MAILER_ENCRYPTION: tls
        APP_MAILER_USER: ''
        APP_MAILER_PASSWORD: ''
        APP_SECRET: 123456789
        APP_WEBSOCKET_BACKEND_PORT: 8080
        APP_WEBSOCKET_FRONTEND_PORT: 3088
        CMD_INIT_AFTER:
        CMD_INIT_BEFORE:
        CMD_INIT_CLEAN:
        CMD_INIT_INSTALLED: 'true'
      image: 'zhex900/orocommerce:test'
      volumes:
        - '/Users/jake/Code/ot-theme:/var/orocommerce-application/src'
      external_links:
        - db
      ports:
        - '99:80'
