styles:
    inputs:
        - 'bundles/menatheme/mena/scss/settings/global-settings.scss'
        - 'bundles/oroproduct/default/scss/variables/product-sticker-config.scss' : '/bundles/menatheme/mena/scss/product-sticker-config.scss'
    output: 'css/layout/mena/styles.css'