placeholders:
    placeholders:
        scripts_before:
            items:
                googletags_templates:
                    order: 1

    items:
       googletags_templates:
            template: MENAThemeBundle:Js:googletags_templates.js.twig